# Generated by Django 5.0.6 on 2024-07-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField()),
                ('job_description', models.TextField()),
                ('technical_skills', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('additional_information', models.TextField()),
                ('job_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='image_gen.joblisting')),
            ],
        ),
    ]
