# Generated by Django 5.0.6 on 2024-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0002_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='no_of_vaccancy',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(default='Negotiable', max_length=100),
        ),
    ]
