# Generated by Django 5.0.6 on 2024-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0003_joblisting_no_of_vaccancy_joblisting_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='career_level',
            field=models.CharField(default='Junior', max_length=100),
        ),
    ]
