# Generated by Django 5.0.6 on 2024-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0004_joblisting_career_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='vac_img',
            field=models.ImageField(blank=True, null=True, upload_to='vaccancy'),
        ),
    ]
