# Generated by Django 5.0.6 on 2024-07-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0005_joblisting_vac_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='apply_at',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
