# Generated by Django 5.0.6 on 2024-07-08 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0006_joblisting_apply_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_gen.industry')),
            ],
        ),
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('Employement_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=50)),
                ('Seniority_level', models.CharField(choices=[('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Team Lead', 'Team Lead'), ('Project Manager', 'Project Manager')], max_length=50)),
                ('about_job', models.TextField()),
                ('salary', models.CharField(default='Negotiable/Not Disclosed', max_length=100)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('no_of_vaccancy', models.CharField(default=1, max_length=10)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('vac_img', models.ImageField(blank=True, null=True, upload_to='vaccancy')),
                ('qualifications', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('Job_views', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_gen.company')),
            ],
        ),
    ]
