# Generated by Django 5.0.6 on 2024-07-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0007_industry_joblisting_company_logo_company_joblistings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDetails',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
