# Generated by Django 5.0.6 on 2024-07-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0008_delete_jobdetails_delete_joblisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobListings',
            new_name='JobListing',
        ),
    ]
