# Generated by Django 5.0.6 on 2024-07-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0009_rename_joblistings_joblisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(help_text='2-3 Years', max_length=10),
        ),
    ]
