# Generated by Django 5.0.6 on 2024-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0010_alter_joblisting_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='Employement_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('On-site . Full-Time', 'On-site . Full-Time'), ('Part-Time', 'Part-Time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
