# Generated by Django 5.0.6 on 2024-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0012_alter_joblisting_employement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='no_of_vaccancy',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
