# Generated by Django 5.0.6 on 2024-07-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0014_additionalinfo_joblisting_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_information',
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
    ]
