# Generated by Django 5.0.6 on 2024-07-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0016_additionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_info', to='image_gen.joblisting'),
        ),
    ]
