# Generated by Django 5.0.6 on 2024-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0017_alter_additionalinfo_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(help_text='2-3 Years', max_length=100),
        ),
    ]
