# Generated by Django 5.0.6 on 2024-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0018_alter_joblisting_options_alter_joblisting_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='about_job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
