# Generated by Django 5.0.6 on 2024-07-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0019_alter_joblisting_about_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='about_job',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='technical_skills',
        ),
    ]
