# Generated by Django 5.0.6 on 2024-07-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0020_remove_joblisting_about_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='Employement_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('On-site Full-Time', 'On-site Full-Time'), ('On-site Part-Time', 'On-site Part-Time'), ('Hybrid Full-Time', 'Hybrid Full-Time'), ('Part-Time', 'Part-Time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Seniority_level',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Team Lead', 'Team Lead'), ('Project Manager', 'Project Manager')], max_length=50, null=True),
        ),
    ]
