# Generated by Django 5.0.6 on 2024-07-11 04:21

import image_gen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0021_alter_joblisting_employement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='established_date',
            field=models.CharField(blank=True, help_text='Enter the year in YYYY format', max_length=4, null=True, validators=[image_gen.models.validate_year_format]),
        ),
    ]
