# Generated by Django 5.0.6 on 2024-07-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0022_alter_company_established_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
