# Generated by Django 5.0.6 on 2024-07-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0023_alter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Employement_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('On-site Full-Time', 'On-site Full-Time'), ('Remote Full-Time', 'Remote Full-Time'), ('On-site Part-Time', 'On-site Part-Time'), ('Remote Part-Time', 'Remote Part-Time'), ('Hybrid Full-Time', 'Hybrid Full-Time'), ('Part-Time', 'Part-Time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='qualifications',
            field=models.ManyToManyField(related_name='job_listings', to='image_gen.qualifications'),
        ),
    ]
