# Generated by Django 5.0.6 on 2024-07-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0024_qualifications_alter_joblisting_employement_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualifications',
            old_name='title',
            new_name='content',
        ),
    ]
