# Generated by Django 5.0.6 on 2024-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0025_rename_title_qualifications_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Responsbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=models.ManyToManyField(related_name='qualifications', to='image_gen.qualifications'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='aboutjob',
            field=models.ManyToManyField(related_name='aboutjob', to='image_gen.aboutjob'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='responsbilities',
            field=models.ManyToManyField(related_name='responsbilities', to='image_gen.responsbilities'),
        ),
    ]
