# Generated by Django 5.0.6 on 2024-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0026_aboutjob_responsbilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_type', models.CharField(blank=True, choices=[('Technical', 'Technical'), ('soft', 'Technical')], max_length=50, null=True)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='image_gen.skill'),
        ),
    ]
