# Generated by Django 5.0.6 on 2024-07-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0027_skill_joblisting_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='aboutjob',
            field=models.ManyToManyField(blank=True, null=True, related_name='aboutjob', to='image_gen.aboutjob'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(blank=True, help_text='2-3 Years', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='qualifications', to='image_gen.qualifications'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='responsbilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsbilities', to='image_gen.responsbilities'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills', to='image_gen.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skills_type',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('soft', 'Technical')], default='Technical', max_length=50, null=True),
        ),
    ]
