# Generated by Django 5.0.6 on 2024-07-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0028_alter_joblisting_aboutjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='aboutjob',
            field=models.ManyToManyField(related_name='aboutjob', to='image_gen.aboutjob'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=models.ManyToManyField(related_name='qualifications', to='image_gen.qualifications'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='responsbilities',
            field=models.ManyToManyField(related_name='responsbilities', to='image_gen.responsbilities'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='image_gen.skill'),
        ),
    ]
