# Generated by Django 5.0.6 on 2024-07-14 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0029_alter_joblisting_aboutjob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='aboutjob',
        ),
        migrations.AddField(
            model_name='aboutjob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_job', to='image_gen.joblisting'),
        ),
    ]
