# Generated by Django 5.0.6 on 2024-07-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0030_remove_joblisting_aboutjob_aboutjob_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfoTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='image_gen.jobinfotitle'),
        ),
    ]
