# Generated by Django 5.0.6 on 2024-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0031_jobinfotitle_alter_additionalinfo_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='header',
        ),
        migrations.AlterField(
            model_name='jobinfotitle',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
