# Generated by Django 5.0.6 on 2024-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0032_remove_additionalinfo_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='hashtags',
            field=models.ManyToManyField(related_name='job_listings', to='image_gen.hashtag'),
        ),
    ]
