# Generated by Django 5.0.6 on 2024-07-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0033_hashtag_joblisting_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='hashtags',
        ),
    ]
