# Generated by Django 5.0.6 on 2024-07-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0034_remove_joblisting_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='responsbilities',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skills',
        ),
        migrations.AddField(
            model_name='company',
            name='specialties',
            field=models.ManyToManyField(related_name='profiles', to='image_gen.specialty'),
        ),
    ]
