# Generated by Django 5.0.6 on 2024-07-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0034_remove_joblisting_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='responsbilities',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skills',
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10 Employees', '1-10 Employees'), ('11-20 Employees', '11-20 Employees'), ('21-50 Employees', '21-50 Employees'), ('51-100 Employees', '51-100 Employees'), ('101-200 Employees', '101-200 Employees'), ('201+ Employees', '201+ Employees')], max_length=50, null=True),
        ),
    ]
