# Generated by Django 5.0.6 on 2024-07-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0035_specialty_remove_joblisting_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='specialties',
            field=models.ManyToManyField(null=True, related_name='profiles', to='image_gen.specialty'),
        ),
    ]
