# Generated by Django 5.0.6 on 2024-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0036_alter_company_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='image_gen.specialty'),
        ),
    ]
