# Generated by Django 5.0.6 on 2024-07-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0037_alter_company_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='specialties',
        ),
    ]
