# Generated by Django 5.0.6 on 2024-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0038_remove_company_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='image_gen.specialty'),
        ),
    ]
