# Generated by Django 5.0.6 on 2024-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0039_company_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='image_gen.skill'),
        ),
    ]
