# Generated by Django 5.0.6 on 2024-07-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0040_joblisting_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10 Employees', '1-10 Employees'), ('11-20 Employees', '11-20 Employees'), ('21-30 Employees', '21-30 Employees'), ('31-50 Employees', '31-50 Employees'), ('51-200 Employees', '51-200 Employees'), ('201-500 Employees', '201-500 Employees')], max_length=50, null=True),
        ),
    ]
