# Generated by Django 5.0.6 on 2024-07-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0041_alter_company_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='has_expired',
            field=models.BooleanField(default=False),
        ),
    ]
