# Generated by Django 5.0.6 on 2024-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0042_alter_company_options_joblisting_has_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='specialties',
        ),
        migrations.AddField(
            model_name='company',
            name='specialities',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterUniqueTogether(
            name='additionalinfo',
            unique_together={('job', 'title')},
        ),
    ]
