# Generated by Django 5.0.6 on 2024-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0043_alter_additionalinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='specialities',
        ),
        migrations.AddField(
            model_name='company',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='specialties', to='image_gen.specialty'),
        ),
    ]
